# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_chisq <- function(peak_ordered, tf_by_peak, target_by_peak, target_ordered, npeaks, peakmat_x, peakmat_i, peakmat_p, peak_cutoff, ngenes, expmat_x, expmat_i, expmat_p, exp_cutoff, nclusters, clusters) {
    .Call('_epiregulon_fast_chisq', PACKAGE = 'epiregulon', peak_ordered, tf_by_peak, target_by_peak, target_ordered, npeaks, peakmat_x, peakmat_i, peakmat_p, peak_cutoff, ngenes, expmat_x, expmat_i, expmat_p, exp_cutoff, nclusters, clusters)
}

fast_wilcox <- function(exprs_x, exprs_i, exprs_p, peak_x, peak_i, peak_p, target_id, tf_id, peak_id, clusters, ngroups) {
    .Call('_epiregulon_fast_wilcox', PACKAGE = 'epiregulon', exprs_x, exprs_i, exprs_p, peak_x, peak_i, peak_p, target_id, tf_id, peak_id, clusters, ngroups)
}

